final Map<String, String> dutch= {
  "language": "Nederlands",
  "languageCode": "nl",
  "languageMnemonic": "english", //options: english,french,italian,spanish

  "setupTitle": "DigiID installatie:",
  "setupWarn": "Het is erg belangrijk om ervoor te zorgen dat u op een veilige plaats bent zonder camera's of mensen die kijken voordat u verdergaat.",
  "setupButtonCreate": "Nieuwe portemonnee",
  "setupButtonRecover": "Herstel portemonnee",

  "setupCreateTitle": "Maak DigiID portemonnee",
  "setupCreateWarn": "Schrijf op papier of graveer in een stukje metaal.\nBewaar dit niet digitaal:",
  "setupCreateTemplate": "Sjabloon Downloaden",
  "setupCreateInstructions": "Klik op de woorden die daarnet zijn verschenen, hou rekenning met de volgorde:",
  "setupCreateButtonWaver": "Ik heb mijn herstelsleutel veilig offline opgeslagen en dit op een veilige plaats",
  "setupCreateFail": "Verkeerde volgorde",
  
  "setupRestoreTitle": "Herstel DigiID portemonnee",
  "setupRestoreInstructions": "kopieer mnemonisch woorden hier:",

  "setupSaveTitle": "DigiID Pincode beveiligen",
  "setupSaveSetPin": "Stel pincode in:",
  "setupSaveSaving":  "Bezig met bewaren van de sleutelwoorden",
  "setupSavePinNote": "*Getallen wijzigen om vinger-tracering te voorkomen.",

  "settingTitle": "Instellingen",
  "settingAllowBiometric": "Biometrie toestaan:",
  "settingStyle": "Stijl(Herstarten is noodzakelijk):",
  "settingLanguage": "Taal:",
  "settingVersion": "Versie:",

  "digiidConfirmTitle": "Bevestig domein",
  "digiidConfirmInstructions": "Geef uw pincode in als de adresbalk overeenkomt met ",
  "digiidConfirmWaiting": "Onderhandelen met site",
  "digiidConfirmBackupInstructions": "Dit is je backup wachtwoord.\nGebruik geen spaties.\n\n",

  "digipassTitle": "DigiPassword generator",
  "digipassSiteHint": "Site domein",
  "digipassInstructionAbove": "Vul het domein hierboven in en vervolgens uw pincode:",
  "digipassInstructionBelow": "Vul het domein hieronder in en vervolgens uw pincode:",
  "digipassNote": "*Op basis van uw account sleutel en de bovenstaande invoer genereert dit een uniek wachtwoord voor u. Als u hetzelfde woord of dezelfde zin een tweede keer invoert, wordt hetzelfde wachtwoord gegenereerd.",
  "digipassPasswordCopy": "Uw wachtwoord (tik om te kopiëren):",
  "digipassSendToWidget1": "Verzenden naar ",
  "digipassSendToWidget2": " plug-in",
  "digipassSendingToWidget1": "Gecodeerd wachtwoord verzenden naar ",
  "digipassSendingToWidget2": " plug-in",	

  "warningInvalidChecksum": "Onjuiste checksum! Bent u zeker dat dit correct is?",
  "warningShortMnemonic1": "Alleen mnemonisch woorden ",
  "warningShortMnemonic2": " bits. mnemonisch woorden zijn korter dan 128 bit deze worden niet aanbevolen!",

  "errorNoCamera": "App heeft geen cameratoestemming!",
  "errorUnknown": "Onbekende fout: ",
  "errorInvalidPin": "Pincode onjuist",
  "errorNoConnection": "Geen connectie",
  "errorNotDigiIDQR": "Ongeldige DigiID QR Code",
  
  "bioSettingsButton": "Ga naar instellingen",
  "bioSettingsDescriptionAndroid": "Uw vingerafdruk is nog niet ingesteld op uw apparaat. Ga naar 'Instellingen> Beveiliging' om uw vingerafdruk toe te voegen.",
  "bioSettingsDescriptionApple": "Schakel uw Touch ID in",
  "bioLockOutTitle":  "Fout in vingerafdruk",
  "bioAuthenticateTitle": "Vingerafdruk vereist",
  "bioAuthenticateDescription": "Authenticatie vereist",
  "bioHint": "Touch Sensor",
  "bioSuccess": "Vingerafdruk herkend",
  "bioFail": "Vingerafdruk niet herkend. Probeer het opnieuw.",

  "alertCopyClip": "Gekopieerd naar het klembord",
  
  "_Back": "Terug",
  "_Submit": "Enter",
  "_Cancel": "Annuleren",
  "_Verify": "Verifiëren",
  "_Warning": "waarschuwing",
  "_Error": "Fout",
  "_Yes": "Ja",
  "_No": "Nee",
  "_UseAnyways": "Gebruik toch maar",
  "_Close": "Sluiten",
  "_Success": "Successvol",
  "_Failed": "Mislukt",
  "_Copy": "Kopiëren",
};
